base: 
  project: Metro-Interstate-Traffic_Analysis
  random_state: 42
  target_col : traffic_volume

data_source: 
  source_data: data_given/Metro_Interstate_Traffic_Volume.csv

get_data:
  connection_string: mongodb+srv://vsuraj25:wulUIUgOO2j0llyg@cluster0.nbfiihk.mongodb.net/?retryWrites=true&w=majority
  database_name: Metro_Interstate_Traffic_Data
  collection_name: traffic_records

load_data:
  raw_dataset_csv: data/raw/traffic_data.csv

validate_data:
  schema: 
    columns: 
      holiday: object
      temp: float64
      rain_1h: float64
      snow_1h: float64
      clouds_all: int64
      weather_main: object
      weather_description: object
      date_time: object
      traffic_volume: int64
    
    no_of_rows: 48204

    no_of_cols: 9 

prepare_data:
  cleaned_data_path: data/prepared/cleaned_traffic_data.csv
  model_data_path: data/prepared/model_traffic_data.csv

split_data:
  train_path: data/processed/train_traffic_data.csv
  test_path: data/processed/test_traffic_data.csv
  test_size: 0.20 

train_evaluate:
  estimators:
    XGBoostRegressor: 
      params:
        min_samples_split: 2
        min_samples_leaf: 2 
        max_depth: 50

  save_model_path: saved_models

  model_reports: model_reports

  reports:
    scores_file : model_reports/scores.json
    params_file : model_reports/params.json
