base: 
  project: Metro-Interstate-Traffic_Analysis
  random_state: 42
  target_col : traffic_volume

data_source: 
  source_data: data_given/Metro_Interstate_Traffic_Volume.csv

get_data:
  connection_string: mongodb+srv://vsuraj25:wulUIUgOO2j0llyg@cluster0.nbfiihk.mongodb.net/?retryWrites=true&w=majority
  database_name: Metro_Interstate_Traffic_Data
  collection_name: traffic_records


load_data:
  raw_dataset_csv: data/raw/traffic_data.csv

split_data:
  train_path: data/processed/train_traffic_data.csv
  test_path: data/processed/test_traffic_data.csv
  test_size: 0.20